In [7]:
import pandas as pd

df = pd.read_excel('data.xlsx')

In [ ]:
df.columns      # This will display the column names of the DataFrame df.

Index(['Transaction ID', 'Date', 'Customer ID', 'Customer Name', 'City',
       'Region', 'Department', 'Product Name', 'Category', 'Quantity',
       'Unit Price', 'Discount Pct', 'Payment Method', 'Status', 'Sales Rep',
       'Rating', 'Gross Amount', 'Discount Amount', 'Net Amount', 'Tax 18pct',
       'Final Amount'],
      dtype='str')

In [ ]:
df.iloc[0:5, 0:5] # iloc is used to select specific rows and columns based on their integer position. In this case, it selects the first 5 rows and the first 5 columns of the DataFrame.

  Transaction ID       Date Customer ID Customer Name       City
0       TXN00001 2023-01-01    CUST0046     Meera Das       Pune
1       TXN00002 2023-01-03    CUST0149   Sunita Shah    Chennai
2       TXN00003 2023-01-04    CUST0068   Arjun Mehta  Ahmedabad
3       TXN00004 2023-01-04    CUST0010   Pooja Kumar  Bangalore
4       TXN00005 2023-01-07    CUST0028   Meera Joshi       Pune

In [ ]:
df[(df["City"] == "Pune") & (df["Gross Amount"] > 30000)] # This will filter the DataFrame to include rows where both conditions are met: the "City" is "Pune" and the "Gross Amount" is greater than 30000.

In [ ]:
df[(df["City"] == "Pune") | (df["Gross Amount"] > 30000)] # This will filter the DataFrame to include rows where either the "City" is "Pune" or the "Gross Amount" is greater than 30000.

,Transaction ID,Date,Customer ID,Customer Name,City,Region,Department,Product Name,Category,Quantity,...,Discount Pct,Payment Method,Status,Sales Rep,Rating,Gross Amount,Discount Amount,Net Amount,Tax 18pct,Final Amount
0,TXN00001,2023-01-01,CUST0046,Meera Das,Pune,North,Electronics,Product_Omega_JFI,Standard,4,...,5,UPI,Completed,Bob Moore,2.0,18606.40,930.32,17676.08,3181.69,20857.77
4,TXN00005,2023-01-07,CUST0028,Meera Joshi,Pune,North,Food & Beverage,Product_Theta_DAI,Standard,12,...,10,Cash,Completed,Alice Black,3.7,13997.16,1399.72,12597.44,2267.54,14864.98
7,TXN00008,2023-01-10,CUST0089,Meera Patel,Pune,East,Home & Garden,Product_Gamma_JBG,Premium,15,...,5,Debit Card,Completed,Hannah Wilson,2.6,36457.20,1822.86,34634.34,6234.18,40868.52
9,TXN00010,2023-01-12,CUST0081,Vikram Patel,Bangalore,West,Home & Garden,Product_Omega_DJA,Budget,9,...,25,Debit Card,Completed,Edward Brown,1.6,42209.10,10552.28,31656.82,5698.23,37355.05
10,TXN00011,2023-01-16,CUST0112,Raj Gupta,Chennai,West,Sports,Product_Gamma_GJD,Premium,9,...,20,Net Banking,Completed,Diana Moore,4.3,31903.11,6380.62,25522.49,4594.05,30116.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,TXN00495,2024-12-19,CUST0064,Neha Kumar,Bangalore,East,Home & Garden,Product_Gamma_BJE,Budget,13,...,5,UPI,Completed,Edward Taylor,3.5,55512.08,2775.60,52736.48,9492.57,62229.05
495,TXN00496,2024-12-19,CUST0031,Priya Verma,Mumbai,West,Sports,Product_Theta_BDD,Budget,11,...,10,Cash,Completed,Fiona Jackson,3.3,39257.68,3925.77,35331.91,6359.74,41691.65
496,TXN00497,2024-12-21,CUST0143,Arjun Joshi,Pune,South,Toys,Product_Alpha_IIH,Premium,17,...,5,Debit Card,Pending,Alice Moore,1.7,77169.29,3858.46,73310.83,13195.95,86506.78
497,TXN00498,2024-12-22,CUST0196,Pooja Joshi,Pune,Central,Electronics,Product_Gamma_EEI,Standard,13,...,5,Debit Card,Pending,Charlie Brown,1.2,9168.12,458.41,8709.71,1567.75,10277.46
499,TXN00500,2024-12-25,CUST0156,Pooja Mehta,Kolkata,North,Clothing,Product_Delta_JGD,Premium,17,...,5,Credit Card,Completed,Fiona White,4.1,51266.05,2563.30,48702.75,8766.49,57469.24

In [ ]:
df[df["Quantity"]>18] # This will filter the DataFrame to include only rows where the "Quantity" column has a value greater than 18.

In [ ]:
df[df["Customer Name"].str.startswith("A")] # str.startswith() is used to check if the string in the "Customer Name" column starts with the letter "A". It returns a boolean Series where True indicates that the condition is met.

,Transaction ID,Date,Customer ID,Customer Name,City,Region,Department,Product Name,Category,Quantity,...,Discount Pct,Payment Method,Status,Sales Rep,Rating,Gross Amount,Discount Amount,Net Amount,Tax 18pct,Final Amount
2,TXN00003,2023-01-04,CUST0068,Arjun Mehta,Ahmedabad,North,Automotive,Product_Sigma_DAG,Budget,7,...,0,Credit Card,Completed,Fiona Moore,2.4,2295.09,0.00,2295.09,413.12,2708.21
13,TXN00014,2023-01-25,CUST0030,Amit Joshi,Kolkata,East,Automotive,Product_Theta_FJB,Premium,10,...,15,Net Banking,Pending,Hannah Jackson,1.7,45243.70,6786.56,38457.14,6922.29,45379.43
16,TXN00017,2023-01-28,CUST0049,Amit Gupta,Delhi,West,Electronics,Product_Gamma_IEA,Standard,17,...,5,Credit Card,Completed,Bob Jackson,1.9,1441.43,72.07,1369.36,246.48,1615.84
21,TXN00022,2023-02-02,CUST0001,Arjun Patel,Mumbai,Central,Toys,Product_Omega_FDI,Standard,4,...,20,Net Banking,Completed,Diana Jackson,4.5,18467.92,3693.58,14774.34,2659.38,17433.72
25,TXN00026,2023-02-10,CUST0185,Amit Singh,Mumbai,West,Automotive,Product_Theta_GDI,Standard,19,...,5,Cash,Completed,Hannah Wilson,3.5,5144.06,257.20,4886.86,879.63,5766.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,TXN00473,2024-11-16,CUST0121,Arjun Mehta,Lucknow,Central,Books,Product_Sigma_HGF,Budget,17,...,15,Debit Card,Completed,Diana Brown,1.2,70426.41,10563.96,59862.45,10775.24,70637.69
473,TXN00474,2024-11-16,CUST0123,Amit Joshi,Bangalore,West,Electronics,Product_Alpha_GGA,Premium,15,...,15,Net Banking,Refunded,Alice Jackson,3.4,53394.30,8009.14,45385.16,8169.33,53554.49
475,TXN00476,2024-11-18,CUST0088,Amit Verma,Ahmedabad,Central,Books,Product_Theta_HCG,Standard,13,...,25,Debit Card,Refunded,Bob Green,2.5,33304.18,8326.04,24978.14,4496.07,29474.21
485,TXN00486,2024-11-30,CUST0148,Amit Kumar,Kolkata,West,Automotive,Product_Sigma_CAI,Standard,14,...,0,Debit Card,Completed,Fiona Black,4.3,15066.52,0.00,15066.52,2711.97,17778.49
496,TXN00497,2024-12-21,CUST0143,Arjun Joshi,Pune,South,Toys,Product_Alpha_IIH,Premium,17,...,5,Debit Card,Pending,Alice Moore,1.7,77169.29,3858.46,73310.83,13195.95,86506.78

In [ ]:
df[~df["Customer Name"].str.startswith("A")]  # ~ is used to reverse the condition

,Transaction ID,Date,Customer ID,Customer Name,City,Region,Department,Product Name,Category,Quantity,...,Discount Pct,Payment Method,Status,Sales Rep,Rating,Gross Amount,Discount Amount,Net Amount,Tax 18pct,Final Amount
0,TXN00001,2023-01-01,CUST0046,Meera Das,Pune,North,Electronics,Product_Omega_JFI,Standard,4,...,5,UPI,Completed,Bob Moore,2.0,18606.40,930.32,17676.08,3181.69,20857.77
1,TXN00002,2023-01-03,CUST0149,Sunita Shah,Chennai,North,Books,Product_Zeta_AGI,Standard,4,...,5,Debit Card,Refunded,Diana Jackson,1.4,15695.12,784.76,14910.36,2683.86,17594.22
3,TXN00004,2023-01-04,CUST0010,Pooja Kumar,Bangalore,West,Home & Garden,Product_Sigma_EHB,Standard,1,...,15,Cash,Completed,Charlie Brown,2.7,4271.00,640.65,3630.35,653.46,4283.81
4,TXN00005,2023-01-07,CUST0028,Meera Joshi,Pune,North,Food & Beverage,Product_Theta_DAI,Standard,12,...,10,Cash,Completed,Alice Black,3.7,13997.16,1399.72,12597.44,2267.54,14864.98
5,TXN00006,2023-01-08,CUST0153,Vikram Das,Lucknow,Central,Home & Garden,Product_Omega_GEG,Budget,13,...,0,UPI,Completed,Hannah Jackson,3.6,24904.49,0.00,24904.49,4482.81,29387.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,TXN00495,2024-12-19,CUST0064,Neha Kumar,Bangalore,East,Home & Garden,Product_Gamma_BJE,Budget,13,...,5,UPI,Completed,Edward Taylor,3.5,55512.08,2775.60,52736.48,9492.57,62229.05
495,TXN00496,2024-12-19,CUST0031,Priya Verma,Mumbai,West,Sports,Product_Theta_BDD,Budget,11,...,10,Cash,Completed,Fiona Jackson,3.3,39257.68,3925.77,35331.91,6359.74,41691.65
497,TXN00498,2024-12-22,CUST0196,Pooja Joshi,Pune,Central,Electronics,Product_Gamma_EEI,Standard,13,...,5,Debit Card,Pending,Charlie Brown,1.2,9168.12,458.41,8709.71,1567.75,10277.46
498,TXN00499,2024-12-23,CUST0107,Neha Singh,Jaipur,South,Sports,Product_Theta_ACD,Budget,6,...,10,Credit Card,Completed,Fiona Green,3.4,17912.52,1791.25,16121.27,2901.83,19023.10
499,TXN00500,2024-12-25,CUST0156,Pooja Mehta,Kolkata,North,Clothing,Product_Delta_JGD,Premium,17,...,5,Credit Card,Completed,Fiona White,4.1,51266.05,2563.30,48702.75,8766.49,57469.24

In [46]:
df.loc[df["Customer Name"] == "Pooja Mehta","Customer Name"] = "Pooja Sharma"  # loc is used to select specific columns based on a condition

In [ ]:
df[~df["Customer Name"].str.startswith("A")] # ~ it is used to reverse the condition

,Transaction ID,Date,Customer ID,Customer Name,City,Region,Department,Product Name,Category,Quantity,...,Discount Pct,Payment Method,Status,Sales Rep,Rating,Gross Amount,Discount Amount,Net Amount,Tax 18pct,Final Amount
0,TXN00001,2023-01-01,CUST0046,Meera Das,Pune,North,Electronics,Product_Omega_JFI,Standard,4,...,5,UPI,Completed,Bob Moore,2.0,18606.40,930.32,17676.08,3181.69,20857.77
1,TXN00002,2023-01-03,CUST0149,Sunita Shah,Chennai,North,Books,Product_Zeta_AGI,Standard,4,...,5,Debit Card,Refunded,Diana Jackson,1.4,15695.12,784.76,14910.36,2683.86,17594.22
3,TXN00004,2023-01-04,CUST0010,Pooja Kumar,Bangalore,West,Home & Garden,Product_Sigma_EHB,Standard,1,...,15,Cash,Completed,Charlie Brown,2.7,4271.00,640.65,3630.35,653.46,4283.81
4,TXN00005,2023-01-07,CUST0028,Meera Joshi,Pune,North,Food & Beverage,Product_Theta_DAI,Standard,12,...,10,Cash,Completed,Alice Black,3.7,13997.16,1399.72,12597.44,2267.54,14864.98
5,TXN00006,2023-01-08,CUST0153,Vikram Das,Lucknow,Central,Home & Garden,Product_Omega_GEG,Budget,13,...,0,UPI,Completed,Hannah Jackson,3.6,24904.49,0.00,24904.49,4482.81,29387.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,TXN00495,2024-12-19,CUST0064,Neha Kumar,Bangalore,East,Home & Garden,Product_Gamma_BJE,Budget,13,...,5,UPI,Completed,Edward Taylor,3.5,55512.08,2775.60,52736.48,9492.57,62229.05
495,TXN00496,2024-12-19,CUST0031,Priya Verma,Mumbai,West,Sports,Product_Theta_BDD,Budget,11,...,10,Cash,Completed,Fiona Jackson,3.3,39257.68,3925.77,35331.91,6359.74,41691.65
497,TXN00498,2024-12-22,CUST0196,Pooja Joshi,Pune,Central,Electronics,Product_Gamma_EEI,Standard,13,...,5,Debit Card,Pending,Charlie Brown,1.2,9168.12,458.41,8709.71,1567.75,10277.46
498,TXN00499,2024-12-23,CUST0107,Neha Singh,Jaipur,South,Sports,Product_Theta_ACD,Budget,6,...,10,Credit Card,Completed,Fiona Green,3.4,17912.52,1791.25,16121.27,2901.83,19023.10
499,TXN00500,2024-12-25,CUST0156,Pooja Sharma,Kolkata,North,Clothing,Product_Delta_JGD,Premium,17,...,5,Credit Card,Completed,Fiona White,4.1,51266.05,2563.30,48702.75,8766.49,57469.24

In [ ]:
df.dropna()  # used to remove missing values/empty cells from the DataFrame

,Transaction ID,Date,Customer ID,Customer Name,City,Region,Department,Product Name,Category,Quantity,...,Discount Pct,Payment Method,Status,Sales Rep,Rating,Gross Amount,Discount Amount,Net Amount,Tax 18pct,Final Amount
0,TXN00001,2023-01-01,CUST0046,Meera Das,Pune,North,Electronics,Product_Omega_JFI,Standard,4,...,5,UPI,Completed,Bob Moore,2.0,18606.40,930.32,17676.08,3181.69,20857.77
1,TXN00002,2023-01-03,CUST0149,Sunita Shah,Chennai,North,Books,Product_Zeta_AGI,Standard,4,...,5,Debit Card,Refunded,Diana Jackson,1.4,15695.12,784.76,14910.36,2683.86,17594.22
2,TXN00003,2023-01-04,CUST0068,Arjun Mehta,Ahmedabad,North,Automotive,Product_Sigma_DAG,Budget,7,...,0,Credit Card,Completed,Fiona Moore,2.4,2295.09,0.00,2295.09,413.12,2708.21
3,TXN00004,2023-01-04,CUST0010,Pooja Kumar,Bangalore,West,Home & Garden,Product_Sigma_EHB,Standard,1,...,15,Cash,Completed,Charlie Brown,2.7,4271.00,640.65,3630.35,653.46,4283.81
4,TXN00005,2023-01-07,CUST0028,Meera Joshi,Pune,North,Food & Beverage,Product_Theta_DAI,Standard,12,...,10,Cash,Completed,Alice Black,3.7,13997.16,1399.72,12597.44,2267.54,14864.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,TXN00496,2024-12-19,CUST0031,Priya Verma,Mumbai,West,Sports,Product_Theta_BDD,Budget,11,...,10,Cash,Completed,Fiona Jackson,3.3,39257.68,3925.77,35331.91,6359.74,41691.65
496,TXN00497,2024-12-21,CUST0143,Arjun Joshi,Pune,South,Toys,Product_Alpha_IIH,Premium,17,...,5,Debit Card,Pending,Alice Moore,1.7,77169.29,3858.46,73310.83,13195.95,86506.78
497,TXN00498,2024-12-22,CUST0196,Pooja Joshi,Pune,Central,Electronics,Product_Gamma_EEI,Standard,13,...,5,Debit Card,Pending,Charlie Brown,1.2,9168.12,458.41,8709.71,1567.75,10277.46
498,TXN00499,2024-12-23,CUST0107,Neha Singh,Jaipur,South,Sports,Product_Theta_ACD,Budget,6,...,10,Credit Card,Completed,Fiona Green,3.4,17912.52,1791.25,16121.27,2901.83,19023.10
499,TXN00500,2024-12-25,CUST0156,Pooja Sharma,Kolkata,North,Clothing,Product_Delta_JGD,Premium,17,...,5,Credit Card,Completed,Fiona White,4.1,51266.05,2563.30,48702.75,8766.49,57469.24

In [ ]:
df.groupby("City")["Gross Amount"].sum()
## So here df.groupby("City") will group the data based on the unique values in the "City" column, and then ["Gross Amount"].sum() will calculate the sum of the "Gross Amount" for each city.

City
Ahmedabad    1152363.65
Bangalore    1336116.21
Chennai      1128533.45
Delhi        1086940.99
Hyderabad     630703.66
Jaipur        998969.62
Kolkata      1671601.64
Lucknow      1453166.26
Mumbai       1568687.98
Pune         1275698.04
Name: Gross Amount, dtype: float64

In [ ]:
df.sort_values("Gross Amount") # This will sort the DataFrame in descending order based on the values in the "Gross Amount" column. The row with the highest "Gross Amount" will appear first.

,Transaction ID,Date,Customer ID,Customer Name,City,Region,Department,Product Name,Category,Quantity,...,Discount Pct,Payment Method,Status,Sales Rep,Rating,Gross Amount,Discount Amount,Net Amount,Tax 18pct,Final Amount
280,TXN00281,2024-01-23,CUST0172,Meera Kumar,Hyderabad,Central,Sports,Product_Theta_IAB,Standard,1,...,20,Cash,Completed,Charlie Jackson,4.3,370.20,74.04,296.16,53.31,349.47
414,TXN00415,2024-08-20,CUST0089,Pooja Das,Chennai,East,Home & Garden,Product_Zeta_AID,Standard,2,...,0,Credit Card,Completed,Edward Brown,2.4,371.46,0.00,371.46,66.86,438.32
98,TXN00099,2023-05-08,CUST0012,Pooja Joshi,Jaipur,Central,Electronics,Product_Gamma_JEJ,Standard,3,...,0,Cash,Completed,Diana Green,2.6,416.49,0.00,416.49,74.97,491.46
278,TXN00279,2024-01-18,CUST0033,Meera Das,Hyderabad,North,Clothing,Product_Alpha_GBD,Standard,2,...,10,UPI,Refunded,George Moore,1.5,423.20,42.32,380.88,68.56,449.44
307,TXN00308,2024-03-08,CUST0051,Vikram Sharma,Bangalore,South,Electronics,Product_Alpha_CED,Standard,8,...,10,UPI,Completed,Edward White,1.7,515.68,51.57,464.11,83.54,547.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,TXN00236,2023-11-03,CUST0170,Pooja Joshi,Bangalore,West,Home & Garden,Product_Theta_GGG,Premium,18,...,5,Cash,Completed,Bob Brown,2.0,87574.32,4378.72,83195.60,14975.21,98170.81
60,TXN00061,2023-03-19,CUST0078,Sanjay Verma,Chennai,Central,Home & Garden,Product_Theta_HCI,Standard,19,...,0,Credit Card,Completed,Edward Moore,2.1,90018.77,0.00,90018.77,16203.38,106222.15
465,TXN00466,2024-11-06,CUST0164,Sunita Das,Lucknow,South,Toys,Product_Zeta_FDA,Standard,19,...,10,Net Banking,Pending,Edward Green,1.3,93129.26,9312.93,83816.33,15086.94,98903.27
303,TXN00304,2024-02-26,CUST0174,Priya Verma,Bangalore,East,Clothing,Product_Omega_ICA,Budget,19,...,10,Credit Card,Pending,Hannah Green,2.0,93480.19,9348.02,84132.17,15143.79,99275.96
457,TXN00458,2024-10-27,CUST0033,Pooja Patel,Kolkata,North,Automotive,Product_Beta_EGB,Budget,19,...,0,Net Banking,Completed,Hannah Green,3.3,94516.45,0.00,94516.45,17012.96,111529.41